OPENROUTER_API_KEY = "your open api key"  # your real OpenRouter key
OPENROUTER_MODEL_NAME = "openai/gpt-oss-20b:free"

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


#GROQ_API_KEY = "gsk-86d7222f0f97d41bba79c67566c92c020326193740342a8e62968d3233fb4e5f"
#GROQ_MODEL_NAME = "llama-3.1-70b-versatile"
#EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"



GEMINI_API_KEY = "YOUR GEMINI API KEY"
GEMINI_MODEL_NAME = "gemini-2.5-flash"   # or gemini-1.5-pro if needed
#EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


