OPENROUTER_API_KEY = "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"  # your real OpenRouter key
OPENROUTER_MODEL_NAME = "openai/gpt-oss-20b:free"

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


#GROQ_API_KEY = "gsk-86d7222f0f97d41bba79c67566c92c020326193740342a8e62968d3233fb4e5f"
#GROQ_MODEL_NAME = "llama-3.1-70b-versatile"
#EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"



GEMINI_API_KEY = "AIzaSyBvw6pMat9US7Oxw10WcDZbzN42ahUlBgA"
GEMINI_MODEL_NAME = "gemini-2.5-flash"   # or gemini-1.5-pro if needed
#EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


